<?php
	if (! empty($_GET['comunidad'])){
		if ($_GET['comunidad'] == "vascongadas") {
		echo "El País Vasco o Euskadi (en euskera: Euskal Herria o Euskadi) es una comunidad autónoma española, situada en el extremo nororiental de la franja cantábrica, lindando al norte con el Golfo de Vizcaya (mar Cantábrico) y Francia (Aquitania), al sur con La Rioja, al oeste con Cantabria y Burgos y al este con Navarra. El País Vasco está reconocido como nacionalidad histórica por su Estatuto de Autonomía. Lo integran las provincias (denominadas territorios históricos en el ordenamiento autonómico) de Álava, Guipúzcoa y Vizcaya.";
		} else if ($_GET['comunidad'] == "valencia") {
		echo "La Comunidad Valenciana (en valenciano y oficialmente, Comunitat Valenciana) es una comunidad autónoma de España, la cual se constituyó como comunidad autónoma en el año 1982, al aprobarse su Estatuto de Autonomía, y desde el año 2006, cuando se reformó el Estatuto, se define a la Comunidad Valenciana como nacionalidad histórica, al amparo de lo dispuesto en el artículo segundo de la Constitución Española.";
		} else if ($_GET['comunidad'] == "navarra") {
		echo "Navarra (en euskera: Nafarroa), denominada oficialmente Comunidad Foral de Navarra (en euskera: Nafarroako Foru Komunitatea), es una comunidad foral española situada en el norte de la Península Ibérica. Limita al norte con Francia (departamento de Pirineos Atlánticos), al este y sureste con la comunidad autónoma de Aragón (provincias de Huesca y Zaragoza), por el sur con la de La Rioja y por el oeste con la del País Vasco (provincias de Álava y Guipúzcoa). Posee un exclave (Petilla de Aragón) rodeado totalmente por la provincia aragonesa de Zaragoza. Es el territorio correspondiente a la Alta Navarra del Renacimiento (la Baja Navarra forma parte de Francia).";
		} else if ($_GET['comunidad'] == "murcia") {
		echo "La Región de Murcia es una comunidad autónoma uniprovincial española, situada en el sudeste de la península ibérica, entre Andalucía (provincias de Granada y Almería) y la Comunidad Valenciana (provincia de Alicante), y entre la costa mediterránea y Castilla-La Mancha (provincia de Albacete). Su capital es la ciudad de Murcia, que es sede de los órganos institucionales regionales, con excepción de la Asamblea Regional, que tiene su sede en Cartagena, razón por la que es denominada como «capital legislativa» en el preámbulo de la ley 5/2005, aunque esta denominación no aparece recogida en el estatuto de autonomía.";
		} else if ($_GET['comunidad'] == "melilla") {
		echo "Melilla (lengua bereber: Mric, Mritch) es una ciudad autónoma de España, situada en el norte de África, a orillas del mar Mediterráneo, frente a la localidad de Adra en el litoral de la provincia de Almería donde se junta con la de Granada, todo ello en la costa meridional oriental de la península Ibérica.";
		} else if ($_GET['comunidad'] == "madrid") {
		echo "La Comunidad de Madrid es una comunidad autónoma de España situada en el centro de la península ibérica y, dentro de esta, en el centro de la Meseta Central. Limita con las provincias de Guadalajara, Cuenca, Toledo (Castilla-La Mancha), Ávila y Segovia (Castilla y León). La Comunidad de Madrid es uniprovincial, por lo que no existe Diputación. Su capital, Madrid, es también la capital de España. Su población es de 6 448 270 habitantes (INE 2013), la cual se concentra en el área metropolitana.";
		} else if ($_GET['comunidad'] == "la-rioja") {
		echo "La Rioja es una comunidad autónoma de España situada en el norte de la península ibérica. Abarca parte del valle del Ebro en su zona septentrional y del sistema Ibérico en el sur. La comunidad es uniprovincial, por lo que no existe Diputación y se encuentra organizada en 174 municipios. La capital es Logroño y su población es de 322.027 habitantes (INE 2013).";
		} else if ($_GET['comunidad'] == "galicia") {
		echo "Galicia es una comunidad autónoma española, situada en el noroeste de la península ibérica y formada por las provincias de La Coruña, Lugo, Orense y Pontevedra, las cuales se dividen en 314 municipios que se agrupan en 53 comarcas. Geográficamente, limita al norte con el mar Cantábrico, al sur con Portugal, al oeste con el océano Atlántico y al este con el Principado de Asturias y con la comunidad de Castilla y León (provincias de Zamora y de León).";
		} else if ($_GET['comunidad'] == "extremadura") {
		echo "Extremadura (Estremaúra en extremeño) es una comunidad autónoma española situada en la zona suroeste de la península ibérica. Está compuesta por las dos provincias más extensas de España: Cáceres y Badajoz. Extremadura limita al norte con las provincias de Salamanca, Ávila (Castilla y León), al sur con Huelva, Sevilla y Córdoba (Andalucía); al este, con Toledo y Ciudad Real (Castilla-La Mancha) y al oeste, con Portugal. Su capital es Mérida (antigua Augusta Emerita), ciudad reconocida por el Estatuto de Autonomía como sede del Gobierno de Extremadura.";
		} else if ($_GET['comunidad'] == "ceuta") {
		echo "Ceuta es una ciudad autónoma de España, situada en la península Tingitana, en la orilla africana del estrecho de Gibraltar, en la desembocadura oriental del mismo. A su vez Ceuta contiene una pequeña península conocida como Almina. Está bañada al norte, al este y al sur por el mar Mediterráneo. Al oeste y suroeste limita con una zona neutral que la separa de Marruecos, concretamente de las prefecturas de Fahs Anjra y M'Diq-Fnideq, ambas pertenecientes a la región Tánger-Tetuán.";
		} else if ($_GET['comunidad'] == "cataluna") {
		echo "Cataluña (en catalán: Catalunya; en aranés: Catalonha) es una comunidad autónoma española considerada como nacionalidad histórica, situada al nordeste de la península ibérica. Ocupa un territorio de unos 32 000 km² que limita al norte con Francia (Mediodía-Pirineos y Languedoc-Rosellón) y Andorra, al este con el mar Mediterráneo a lo largo de una franja marítima de unos 580 kilómetros, al sur con la Comunidad Valenciana, y al oeste con Aragón. Esta situación estratégica ha favorecido una relación muy intensa con los territorios de la cuenca mediterránea y con la Europa continental. Cataluña está formada por las provincias de Barcelona, Gerona, Lérida y Tarragona. Su capital es la ciudad de Barcelona.";
		} else if ($_GET['comunidad'] == "castilla-leon") {
		echo "Castilla y León es una comunidad autónoma española, referida como «comunidad histórica» y «cultural» en su Estatuto de Autonomía. Se constituyó formalmente en 1979 y adquirió su estatus plenamente efectivo en 1983. Su territorio se sitúa en la parte norte de la meseta de la península ibérica y se corresponde mayoritariamente con la parte española de la cuenca hidrográfica del Duero. Está compuesta por nueve provincias: Ávila, Burgos, León, Palencia, Salamanca, Segovia, Soria, Valladolid y Zamora.";
		} else if ($_GET['comunidad'] == "castilla-la-mancha") {
		echo "Castilla-La Mancha es una comunidad autónoma de España, de acuerdo con su Estatuto de Autonomía y la Constitución Española. Está formada por los 919 municipios que integran las provincias de Albacete, Ciudad Real, Cuenca, Guadalajara y Toledo. Albacete es su ciudad más grande y más poblada. Su capital es la ciudad de Toledo, sede de la Junta de Comunidades de Castilla-La Mancha, máximo órgano del autogobierno de la Comunidad, siendo la ciudad de Albacete la que alberga el máximo órgano judicial, el Tribunal Superior de Justicia de Castilla-La Mancha.";
		} else if ($_GET['comunidad'] == "cantabria") {
		echo "Cantabria es una comunidad autónoma española de carácter uniprovincial referida como «comunidad histórica» en su Estatuto de Autonomía. Limita al este con el País Vasco (provincia de Vizcaya), al sur con Castilla y León (provincias de León, Palencia y Burgos), al oeste con el Principado de Asturias y al norte con el mar Cantábrico. La ciudad de Santander es su capital y localidad más poblada.";
		} else if ($_GET['comunidad'] == "canarias") {
		echo "Canarias es un archipiélago del océano Atlántico que conforma una de las diecisiete comunidades autónomas de España, y una de las regiones ultraperiféricas de la Unión Europea. Se compone de siete islas principales: El Hierro, La Gomera, La Palma y Tenerife, que forman la provincia de Santa Cruz de Tenerife; y Fuerteventura, Gran Canaria y Lanzarote, que constituyen la provincia de Las Palmas. También forman parte de Canarias los territorios insulares del Archipiélago Chinijo (La Graciosa, Alegranza, Montaña Clara, Roque del Este y Roque del Oeste) y la Isla de Lobos, todos ellos pertenecientes a la provincia de Las Palmas. La Graciosa es la única de estas islas que está habitada.";
		} else if ($_GET['comunidad'] == "baleares") {
		echo "Las Islas Baleares (en catalán y oficialmente, Illes Balears) son una comunidad autónoma uniprovincial española, compuesta por las islas del archipiélago balear. Se encuentran situadas en el mar Mediterráneo, frente a la costa oriental de la península ibérica. Su capital es Palma de Mallorca.";
		} else if ($_GET['comunidad'] == "asturias") {
		echo "Asturias, denominada oficialmente Principado de Asturias (en asturiano, Principáu d'Asturies; en eonaviego, Principao d'Asturias), es una comunidad autónoma uniprovincial de España. Situada en el norte de España ocupa un área total de 10 603,57 km², en el que habitan 1 054 408 personas (INE, 2014). Fronteriza al oeste con la provincia de Lugo (Galicia), al norte con el mar Cantábrico, al este con Cantabria y al sur con la provincia de León (Castilla y León). Recibe el nombre de Principado por razones históricas, al ostentar el heredero de la Corona de España el título nobiliario de «Príncipe de Asturias», establecido por Juan I de Castilla en el año 1388. Su capital es la ciudad de Oviedo, mientras que Gijón es su ciudad más poblada.";
		} else if ($_GET['comunidad'] == "aragon") {
		echo "Aragón (Aragón en aragonés, Aragó en catalán) es una comunidad autónoma de España, resultante del reino histórico del mismo nombre y que comprende el tramo central del valle del Ebro, los Pirineos centrales y las Sierras Ibéricas. Está situada en el norte de España, y limita por el norte con Francia, por el oeste con las comunidades autónomas de Castilla-La Mancha, Castilla y León, La Rioja, Navarra y por el este con Cataluña y la Comunidad Valenciana. Está definida en su Estatuto de autonomía como nacionalidad histórica.";
		} else if ($_GET['comunidad'] == "andalucia") {
		echo "Andalucía es una comunidad autónoma de España, con estatus de nacionalidad histórica, de acuerdo con el Estatuto de Autonomía que la rige. Está compuesta por las provincias de Almería, Cádiz, Córdoba, Granada, Huelva, Jaén, Málaga y Sevilla. Su capital es Sevilla, ciudad reconocida por el Estatuto de Autonomía como sede de la Junta de Andalucía. La sede del Tribunal Superior de Justicia de Andalucía se encuentra en la ciudad de Granada.";
		} else {
		echo "Desconocido.";
		}
	}
?>

